In [4]:
# Importamos librerías necesarías para la solución
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# Asignamos el documento csv a un dataframe llamadado 'datos'
datos = pd.read_csv("covid19_tweets.csv")

In [5]:
# Vemos la estadística básica de 'datos'
datos.describe()

       user_followers   user_friends  user_favourites
count    7.443600e+04   74436.000000     7.443600e+04
mean     1.059513e+05    2154.721170     1.529747e+04
std      8.222900e+05    9365.587474     4.668971e+04
min      0.000000e+00       0.000000     0.000000e+00
25%      1.660000e+02     153.000000     2.200000e+02
50%      9.600000e+02     552.000000     1.927000e+03
75%      5.148000e+03    1780.250000     1.014800e+04
max      1.389284e+07  497363.000000     2.047197e+06

In [7]:
# Followers
# Max número de seguidores: 13 892 840

sub_df_followers = data[data['user_followers'] > 12000000]

sub_df_followers[['user_name','user_followers','hashtags']].head()

0        False
1        False
2        False
3        False
4        False
         ...
74431    False
74432    False
74433    False
74434    False
74435    False
Name: user_followers, Length: 74436, dtype: bool
                user_name                  user_location  \
235                  CGTN                 Beijing, China
785    The Times Of India                      New Delhi
1161                 NDTV                          India
1354                 NDTV                          India
2837                 CGTN                 Beijing, China
...                   ...                            ...
70960   China Xinhua News  Headquartered in Beijing, PRC
73149   China Xinhua News  Headquartered in Beijing, PRC
73331                NDTV                          India
73350                NDTV                          India
73686                CGTN                 Beijing, China

                                        user_description         user_created  \
235    #SeeTheDifference with CGTN as we bring you st...  2013-01-24 03:18:59
785    News. Views. Analysis. Conversations. India’s ...  2010-04-19 10:50:15
1161   Breaking news alerts from India.\n\nInstagram:...  2009-05-01 20:34:48
1354   Breaking news alerts from India.\n\nInstagram:...  2009-05-01 20:34:48
2837   #SeeTheDifference with CGTN as we bring you st...  2013-01-24 03:18:59
...                                                  ...                  ...
70960  We are public media for the public good. We do...  2012-02-09 01:10:18
73149  We are public media for the public good. We do...  2012-02-09 01:10:18
73331  Breaking news alerts from India.\n\nInstagram:...  2009-05-01 20:34:48
73350  Breaking news alerts from India.\n\nInstagram:...  2009-05-01 20:34:48
73686  #SeeTheDifference with CGTN as we bring you st...  2013-01-24 03:18:59

       user_followers  user_friends  user_favourites  user_verified  \
235          13892795            69              104           True
785          12978547           505                5           True
1161         13417047            15                0           True
1354         13417047            15                0           True
2837         13892793            69              104           True
...               ...           ...              ...            ...
70960        12677810            64                0           True
73149        12677807            64                0           True
73331        13449823            15                1           True
73350        13449823            15                1           True
73686        13882338            69              120           True

                      date                                               text  \
235    2020-07-25 12:20:00  #APEC reaffirms #COVID19 economic recovery pri...
785    2020-07-25 12:02:41  Rajasthan Government today started a Plasma Ba...
1161   2020-07-25 11:52:54  #RajasthanPoliticalCrisis | As Ashok Gehlot me...
1354   2020-07-25 11:45:36  #RajasthanPoliticalCrisis | BJP delegation arr...
2837   2020-07-25 10:46:35  #COVID19 recovery can take weeks even for youn...
...                    ...                                                ...
70960  2020-08-04 05:36:27  Live COVID-19 updates, Aug. 4: https://t.co/Oe...
73149  2020-08-04 04:05:36  Rowing bamboo rafts on Cisadane river, Indones...
73331  2020-08-04 03:59:12  US Adds Over 46,000 #COVID19 Cases In Last 24 ...
73350  2020-08-04 03:58:37  India's #COVID19 Tally Crosses 18-Lakh Mark; O...
73686  2020-08-04 03:44:21  #Chinese mainland reports 36 new #COVID19 case...

                           hashtags                          source  \
235             ['APEC', 'COVID19']                       TweetDeck
785                             NaN                       TweetDeck
1161   ['RajasthanPoliticalCrisis']  Twitter Media Studio - LiveCut
1354   ['RajasthanPoliticalCrisis']                 Twitter Web App
2837                    ['COVID19']                 Twitter Web App
...                             ...                             ...
70960               ['coronavirus']               China Xinhua News
73149                           NaN               China Xinhua News
73331                   ['COVID19']                 Twitter Web App
73350                   ['COVID19']                 Twitter Web App
73686        ['Chinese', 'COVID19']                 Twitter Web App

       is_retweet
235         False
785         False
1161        False
1354        False
2837        False
...           ...
70960       False
73149       False
73331       False
73350       False
73686       False

[156 rows x 13 columns]